# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# trigger:
# - main
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - "Dockerfile*"
      - "*__init__.py*"

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: "3.7"

steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: "Azure subscription 1 (858549e2-8aab-4d4f-ad8d-d87e01785d46)"
      KeyVaultName: "workflow-poc-kv001"
      SecretsFilter: "*"
      RunAsPreJob: false
    displayName: "Pull Azure Secrets"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: "pytest"

  - script: |
      set -e
      prefect auth login --key nfW68HN5uyUbN1HpFEGVuA
      prefect create project dev-workflow-poc --skip-if-exists
      prefect register --project dev-workflow-poc --label prefect --path $(Build.Repository.LocalPath)/flows
    displayName: flow register
    env:
      AZURE_CLIENT_ID: $(workflow-poc-sp-client-id)
      AZURE_TENANT_ID: $(workflow-poc-sp-tenant-id)
      AZURE_CLIENT_SECRET: $(workflow-poc-sp-secret)
      PYTHONPATH: "${PYTHONPATH}:$(Build.Repository.LocalPath)/flow_utils/"
