# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# trigger:
# - main
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - "Dockerfile*"
      - "*__init__.py*"
      - "prefect-agent.yml"
      - "docker-pipeline.yml"

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  displayName: 'Build and test'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: "Azure subscription 1 (858549e2-8aab-4d4f-ad8d-d87e01785d46)"
          KeyVaultName: "workflow-poc-kv001"
          SecretsFilter: "*"
          RunAsPreJob: false
        displayName: "Pull Azure Secrets"
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7.x' 
          addToPath: true 
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        displayName: "pytest"

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  # condition: |
  #   and
  #   (
  #     succeeded(),
  #     eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
  #   )
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
            - template: flow-deploy-template.yml
              parameters:
                env: $(Environment.name)
