# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
     include:
        - main
  paths:
    include:
      - 'Dockerfile'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'workflow-acr'
    repository: 'prefect-repo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- task: KubernetesManifest@0
  displayName: deploy
  inputs:
    kubernetesServiceConnection: 'workflow-poc-k8s'
    manifests: 'prefect-agent.yml'
    rolloutStatusTimeout: 300